name: Record Temperature Update

on:
  schedule:
    - cron: '0 19 * * *'
  push:
    branches: ["main"]

jobs:
  update-temperature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen tr_TR.UTF-8
          sudo update-locale LANG=tr_TR.UTF-8
        shell: bash

      - name: Run script
        run: |
          python -c "
          import datetime
          import RecordAnalyze
          now = datetime.datetime.now()
          RecordAnalyze.Monthly(now.day, now.month, now.year).maxTemp_to_csv()
          "

      - name: Move results to directory
        run: |
          mkdir -p results
          mv *.csv results/

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m 'Added record check csv file for $(date +'%Y-%m-%d')'
          git push
